// mini-exam-web/client/src/views/Login.vue
<template>
  <div class="login-container">
    <div class="login-header">
      <h1 class="login-title">📝 迷你自测</h1>
      <p class="login-subtitle">在线练习，自我提升</p>
    </div>
    
    <div class="login-card">
      <div class="login-tabs">
        <button 
          class="login-tab" 
          :class="{ active: isLogin }"
          @click="isLogin = true"
        >登录</button>
        <button 
          class="login-tab" 
          :class="{ active: !isLogin }"
          @click="isLogin = false"
        >注册</button>
      </div>
      
      <div class="login-form">
        <div class="form-group">
          <label class="form-label">用户名</label>
          <input 
            v-model="form.username" 
            type="text" 
            class="form-input" 
            placeholder="请输入用户名"
            @keyup.enter="submit"
          >
        </div>
        
        <div class="form-group">
          <label class="form-label">密码</label>
          <input 
            v-model="form.password" 
            type="password" 
            class="form-input" 
            placeholder="请输入密码"
            @keyup.enter="submit"
          >
        </div>
        
        <div v-if="!isLogin" class="form-group">
          <label class="form-label">确认密码</label>
          <input 
            v-model="form.confirmPassword" 
            type="password" 
            class="form-input" 
            placeholder="请再次输入密码"
            @keyup.enter="submit"
          >
        </div>
        
        <div v-if="errorMsg" class="alert alert-danger">{{ errorMsg }}</div>
        
        <button 
          class="btn btn-primary" 
          style="width: 100%; height: 48px; font-size: 16px; margin-top: 8px;"
          @click="submit"
          :disabled="loading"
        >
          {{ loading ? '处理中...' : (isLogin ? '登 录' : '注 册') }}
        </button>
      </div>
      
      <div class="login-tip">
        <p>🔐 默认管理员：<strong>admin / admin123</strong></p>
        <p style="margin-top: 4px;">📱 或注册新账号体验</p>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, reactive } from 'vue'
import { useRouter } from 'vue-router'
import http from '../utils/http.js'
import userStore from '../store/user.js'

const router = useRouter()
const isLogin = ref(true)
const loading = ref(false)
const errorMsg = ref('')

const form = reactive({
  username: '',
  password: '',
  confirmPassword: ''
})

const submit = async () => {
  errorMsg.value = ''
  
  if (!form.username.trim()) {
    errorMsg.value = '请输入用户名'
    return
  }
  if (!form.password.trim()) {
    errorMsg.value = '请输入密码'
    return
  }
  if (!isLogin.value && form.password !== form.confirmPassword) {
    errorMsg.value = '两次密码不一致'
    return
  }
  
  loading.value = true
  
  try {
    const url = isLogin.value ? '/api/auth/login' : '/api/auth/register'
    const res = await http.post(url, {
      username: form.username.trim(),
      password: form.password
    })
    
    if (res.data.success) {
      userStore.setAuth(res.data.data.token, res.data.data.user)
      router.push('/')
    } else {
      errorMsg.value = res.data.message
    }
  } catch (err) {
    errorMsg.value = err.response?.data?.message || '请求失败，请重试'
  } finally {
    loading.value = false
  }
}
</script>

<style scoped>
.login-container {
  min-height: 100vh;
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  padding: 24px 16px;
  box-sizing: border-box;
}

.login-header {
  text-align: center;
  margin-bottom: 24px;
}

.login-title {
  font-size: 28px;
  color: #fff;
  margin: 0;
  font-weight: 700;
}

.login-subtitle {
  font-size: 14px;
  color: rgba(255, 255, 255, 0.85);
  margin: 8px 0 0 0;
}

.login-card {
  width: 100%;
  max-width: 400px;
  background: #fff;
  border-radius: 20px;
  padding: 24px 20px;
  box-shadow: 0 10px 40px rgba(0, 0, 0, 0.2);
}

.login-tabs {
  display: flex;
  background: #f5f7fa;
  border-radius: 12px;
  padding: 4px;
  margin-bottom: 24px;
}

.login-tab {
  flex: 1;
  padding: 12px 16px;
  border: none;
  background: transparent;
  border-radius: 8px;
  font-size: 16px;
  font-weight: 600;
  color: #909399;
  cursor: pointer;
  transition: all 0.3s ease;
}

.login-tab.active {
  background: #fff;
  color: #409eff;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
}

.login-form {
  margin-bottom: 20px;
}

.login-tip {
  background: #f5f7fa;
  border-radius: 12px;
  padding: 12px;
  font-size: 12px;
  color: #606266;
  margin-top: 16px;
}

.login-tip p {
  margin: 0;
}
</style>

// feedback-factory/src/pages/login.tsx
import { useState, useEffect } from 'react';
import Head from 'next/head';
import Link from 'next/link';
import { useRouter } from 'next/router';

export default function Login() {
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const router = useRouter();

  useEffect(() => {
    checkAuth();
  }, []);

  const checkAuth = async () => {
    try {
      const response = await fetch('/api/auth/me');
      if (response.ok) {
        router.push('/admin');
      }
    } catch {
      // 未登录，留在登录页
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    setError('');

    try {
      const response = await fetch('/api/auth/login', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ username, password }),
      });

      const data = await response.json();
      if (response.ok) {
        router.push('/admin');
      } else {
        setError(data.error || '登录失败');
      }
    } catch (err) {
      setError('网络错误，请稍后重试');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-gray-50 flex items-center justify-center px-4">
      <Head>
        <title>管理员登录 - Feedback Factory</title>
        <meta name="description" content="管理员登录" />
      </Head>

      <div className="w-full max-w-md">
        <div className="text-center mb-8">
          <h1 className="text-3xl font-bold text-gray-800 mb-2">📝 Feedback Factory</h1>
          <p className="text-gray-600">管理后台登录</p>
        </div>

        <div className="bg-white rounded-lg shadow-md p-6 md:p-8">
          {error && (
            <div className="mb-6 p-4 bg-red-50 border border-red-200 rounded-lg text-red-700 text-sm">
              {error}
            </div>
          )}

          <form onSubmit={handleSubmit} className="space-y-6">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                用户名
              </label>
              <input
                type="text"
                value={username}
                onChange={(e) => setUsername(e.target.value)}
                placeholder="请输入用户名"
                className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent outline-none transition"
                required
                autoComplete="username"
              />
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                密码
              </label>
              <input
                type="password"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                placeholder="请输入密码"
                className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent outline-none transition"
                required
                autoComplete="current-password"
              />
            </div>

            <button
              type="submit"
              disabled={loading}
              className="w-full bg-blue-600 text-white py-3 px-6 rounded-lg font-medium hover:bg-blue-700 focus:ring-4 focus:ring-blue-200 transition disabled:opacity-50 disabled:cursor-not-allowed"
            >
              {loading ? '登录中...' : '登录'}
            </button>
          </form>

          <div className="mt-6 pt-6 border-t border-gray-100">
            <p className="text-sm text-gray-500 text-center">
              默认账号：<span className="font-mono text-gray-700">admin</span> / <span className="font-mono text-gray-700">admin123</span>
            </p>
            <p className="text-xs text-gray-400 text-center mt-2">
              可通过环境变量 ADMIN_USERNAME 和 ADMIN_PASSWORD 自定义
            </p>
          </div>
        </div>

        <div className="mt-6 text-center">
          <Link
            href="/"
            className="text-sm text-blue-600 hover:text-blue-800"
          >
            ← 返回首页
          </Link>
        </div>
      </div>
    </div>
  );
}
